---
title: "DataCleaning"
author: "SIR"
date: "May 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(data.table)
```

#We are not using the direct data from instacart as it is too big. Therefore you can download the data from this link as per the analysis of this project we refer to this data: `https://p8105.com/dataset_instacart.html`
```{r cars}
#read/import the file  that we use
df <- fread("./orders_train_allvars.csv")
```


```{r }
#Selecting only the columns We need to use for this project. Keep in mind we are using train dataset only.
insta<-df%>%
  select(order_id, order_number, user_id, reordered, add_to_cart_order, order_dow, order_hour_of_day, product_name, aisle, department, days_since_prior_order)
```

```{r }
#counting how many unique values each column has
insta %>% summarise_all(list(~n_distinct(.)))
```

```{r }
#here I am removing missing department values which does not make sense
insta<-insta[!(insta$department=="missing"),]
```

```{r}

#Here I am replacing cart priority ordering with sub categories so that improve efficiency later on when drawing graphs.
  insta$add_to_cart_order <- 
  ifelse(insta$add_to_cart_order >= 1 & insta$add_to_cart_order <=4, 'Highest',
  ifelse(insta$add_to_cart_order >= 5 & insta$add_to_cart_order <=10, 'High',
  ifelse(insta$add_to_cart_order >= 11 & insta$add_to_cart_order <18, 'Medium', 
  ifelse(insta$add_to_cart_order >= 18 & insta$add_to_cart_order <25, 'Low', 
  ifelse(insta$add_to_cart_order >= 25, 'Lowest', NA      )))))

```

```{r}

#Here I am changing days of the week from numeric to string/ character
  insta$order_dow <- 
  ifelse(insta$order_dow == 0 , 'Sat',
  ifelse(insta$order_dow == 1 , 'Sun',
  ifelse(insta$order_dow == 2 , 'Mon', 
  ifelse(insta$order_dow == 3 , 'Tue', 
  ifelse(insta$order_dow == 4,  'Wed', 
  ifelse(insta$order_dow == 5,  'Thur',
  ifelse(insta$order_dow == 6,  'Fri', NA)))))))

insta$reordered <- 
  ifelse(insta$reordered == 0 , 'NO',
  ifelse(insta$reordered == 1 , 'YES', NA))

```



```{r }
write.csv(insta,"C:/Users/Ibragim/Desktop/Super final/insta_ready.csv", row.names = FALSE )

```

# We are done with data cleaning and we have saved insta_ready.csv which we will use for our project in shiny


















